### ISSUE TITLE
link for ironsource for all buttons

### ISSUE THREAD

**Issue by shacharoz** [amsh-dev-team/Ad-Adida-Feb-2019#11]
the end version should direct all trafic from buttons to this link
https://www.adidas.co.il/no-fakers

**Comment by amirblum** [comment]
I have explained this to Amit and Dan. The plugin is configured to forward the clicks to a link that will be set up when the ad is implemented in the ironSource platform. This allows for changing the link later, or for setting separate link for iOS/Android. In the meantime it redirects to "test" link and this is expected behavior. You can close this issue.

**Comment by shacharoz** [comment]
ahhh you already have put the right link in the system?
