### ISSUE TITLE
landscape phone shows the ad in a bad way

### ISSUE THREAD

**Issue by shacharoz** [amsh-dev-team/Ad-Adida-Feb-2019#4]
construct forces the ad to be portrait. but ironsource allows landscape,

we need to allow the ad to turn when in landscape mode,

![image](https://user-images.githubusercontent.com/593642/52539075-3e89f780-2d7a-11e9-94f0-ab64ccd2f6be.png)

**Comment by shacharoz** [comment]
added a fix to the project properties:
scale to inner integer + landscape /portrait 

![image](https://user-images.githubusercontent.com/593642/52540457-e5c25b00-2d89-11e9-9ff3-2f243a6109ac.png)

**Comment by amirblum** [comment]
Hey, this is not a good solution unfortunately because now the resolution is fixed even for different portrait resolutions. The "proper" solution is what I told Igloo at the start of development - that this will be a portrait-only ad. We need to figure out if there's a way to set this in the ironSource framework, and if not we need to add a layer that says "please rotate device" and show that if we detect landscape resolution.
